import {  Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import LenisProvider from "@/providers/LenisProvider";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import ContactPopup from "@/components/layout/ContactPopup";
import Snackbar from "@/components/layout/Snackbar";
const cormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-cormorant",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={cormorantGaramond.variable}>
      <body>
        <LenisProvider>
          <Snackbar/>
          <Navbar/>
          {children}
          <Footer/>
        </LenisProvider>
        {/* <ContactPopup/> */}
      </body>
    </html>
  );
}
